services:
  kufibot-cross:
    build:
      context: .
      dockerfile: Dockerfile.cross  # Use the cross-compilation Dockerfile
    container_name: kufibot_cross_env
    working_dir: /app/kufibot.cpp
    volumes:
      - ./src:/app/kufibot.cpp/src
      - ./config:/app/kufibot.cpp/config
      - ./CMakeLists.txt:/app/kufibot.cpp/CMakeLists.txt
      - ./arm64Build.cmake:/app/kufibot.cpp/arm64Build.cmake
      - ./README.md:/app/kufibot.cpp/README.md
      - ./runKufi.sh:/app/kufibot.cpp/runKufi.sh
      - ./kufiDev.sh:/app/kufibot.cpp/kufiDev.sh
      - ~/.ssh:/root/.ssh   # <-- SSH anahtarlarını konteynıra geçir
    tty: true
    stdin_open: true
    environment:
      - TERM=xterm-256color
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - LD_LIBRARY_PATH=/app/kufibot.cpp/lib
      - QEMU_LD_PREFIX=/usr/aarch64-linux-gnu  # Important for cross-compilation
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    command: >
      bash -c "
        chmod 700 /root/.ssh &&
        chmod 600 /root/.ssh/id_rsa &&
        chmod 644 /root/.ssh/id_rsa.pub &&
        [ -f /root/.ssh/config ] && chmod 600 /root/.ssh/config;
        bash
      "