version: '3.9'

services:
  kufibot:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
    platform: linux/arm64
    container_name: kufibot_env
    working_dir: /app/kufibot.cpp
    volumes:
      - .:/app/kufibot.cpp
    tty: true
    stdin_open: true
    network_mode: host
    environment:
      - TERM:xterm-256color
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - LD_LIBRARY_PATH=/app/kufibot.cpp/lib

    devices:
      - /dev/tty:/dev/tty
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1
    group_add:
      - video
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined

